// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wires

import (
	"com.github.gin-common/app/service"
	"com.github.gin-common/app/service/impl"
	"com.github.gin-common/common/controllers"
	"github.com/google/wire"
)

// Injectors from injector.go.bak:

func CreateUserController() controllers.Controller {
	createUserForm := provideCreateUserForm()
	wiresGormSessionTimeout := provideGormSessionTimeout()
	wiresTimeoutGormContext := provideTimeoutGormContext(wiresGormSessionTimeout)
	db := provideTimeoutGormSession(wiresTimeoutGormContext)
	userServiceImpl := provideUserService(db)
	controller := provideCreateUserController(createUserForm, userServiceImpl)
	return controller
}

func UpdateUserController() controllers.Controller {
	updateUserForm := provideUpdateUserForm()
	wiresGormSessionTimeout := provideGormSessionTimeout()
	wiresTimeoutGormContext := provideTimeoutGormContext(wiresGormSessionTimeout)
	db := provideTimeoutGormSession(wiresTimeoutGormContext)
	userServiceImpl := provideUserService(db)
	controller := provideEditUserController(updateUserForm, userServiceImpl)
	return controller
}

func DeleteUserController() controllers.Controller {
	wiresGormSessionTimeout := provideGormSessionTimeout()
	wiresTimeoutGormContext := provideTimeoutGormContext(wiresGormSessionTimeout)
	db := provideTimeoutGormSession(wiresTimeoutGormContext)
	userServiceImpl := provideUserService(db)
	controller := provideDeleteUserController(userServiceImpl)
	return controller
}

func ActivateUserController() controllers.Controller {
	wiresGormSessionTimeout := provideGormSessionTimeout()
	wiresTimeoutGormContext := provideTimeoutGormContext(wiresGormSessionTimeout)
	db := provideTimeoutGormSession(wiresTimeoutGormContext)
	userServiceImpl := provideUserService(db)
	controller := provideActivateUserController(userServiceImpl)
	return controller
}

func DeActivateUserController() controllers.Controller {
	wiresGormSessionTimeout := provideGormSessionTimeout()
	wiresTimeoutGormContext := provideTimeoutGormContext(wiresGormSessionTimeout)
	db := provideTimeoutGormSession(wiresTimeoutGormContext)
	userServiceImpl := provideUserService(db)
	controller := provideDeActivateUserController(userServiceImpl)
	return controller
}

func GetUserInfoController() controllers.Controller {
	wiresGormSessionTimeout := provideGormSessionTimeout()
	wiresTimeoutGormContext := provideTimeoutGormContext(wiresGormSessionTimeout)
	db := provideTimeoutGormSession(wiresTimeoutGormContext)
	userServiceImpl := provideUserService(db)
	controller := provideGetUserInfoController(userServiceImpl)
	return controller
}

func ChangePasswordController() controllers.Controller {
	changePassForm := provideChangePassForm()
	wiresGormSessionTimeout := provideGormSessionTimeout()
	wiresTimeoutGormContext := provideTimeoutGormContext(wiresGormSessionTimeout)
	db := provideTimeoutGormSession(wiresTimeoutGormContext)
	userServiceImpl := provideUserService(db)
	controller := provideChangePasswordController(changePassForm, userServiceImpl)
	return controller
}

func AuthMiddleware() controllers.MiddleWare {
	context := provideRedisContext()
	client := provideRedisRdb()
	wiresGormSessionTimeout := provideGormSessionTimeout()
	wiresTimeoutGormContext := provideTimeoutGormContext(wiresGormSessionTimeout)
	db := provideTimeoutGormSession(wiresTimeoutGormContext)
	userServiceImpl := provideUserService(db)
	middleWare := provideAuthMiddleware(context, client, userServiceImpl)
	return middleWare
}

func DeactivatedAbortMiddleware() controllers.MiddleWare {
	middleWare := provideDeactivatedAbortMiddleware()
	return middleWare
}

func LoginController() controllers.Controller {
	loginForm := provideLoginForm()
	context := provideRedisContext()
	client := provideRedisRdb()
	wiresGormSessionTimeout := provideGormSessionTimeout()
	wiresTimeoutGormContext := provideTimeoutGormContext(wiresGormSessionTimeout)
	db := provideTimeoutGormSession(wiresTimeoutGormContext)
	userServiceImpl := provideUserService(db)
	authServiceImpl := provideAuthService(context, client, userServiceImpl)
	controller := provideLoginController(loginForm, authServiceImpl)
	return controller
}

func LogoutController() controllers.Controller {
	context := provideRedisContext()
	client := provideRedisRdb()
	wiresGormSessionTimeout := provideGormSessionTimeout()
	wiresTimeoutGormContext := provideTimeoutGormContext(wiresGormSessionTimeout)
	db := provideTimeoutGormSession(wiresTimeoutGormContext)
	userServiceImpl := provideUserService(db)
	authServiceImpl := provideAuthService(context, client, userServiceImpl)
	controller := provideLogoutController(authServiceImpl)
	return controller
}

func CurrentUserController() controllers.Controller {
	controller := provideCurrentUserController()
	return controller
}

func CreateBookController() controllers.Controller {
	creatBookForm := provideCreatBookForm()
	wiresGormSessionTimeout := provideGormSessionTimeout()
	wiresTimeoutGormContext := provideTimeoutGormContext(wiresGormSessionTimeout)
	db := provideTimeoutGormSession(wiresTimeoutGormContext)
	bookServiceImpl := provideBookService(db)
	controller := provideCreateBookController(creatBookForm, bookServiceImpl)
	return controller
}

// injector.go.bak:

var sessionSet = wire.NewSet(provideGormSessionTimeout, provideTimeoutGormContext, provideTimeoutGormSession)

var redisSet = wire.NewSet(provideRedisRdb, provideRedisContext)

var userServiceSet = wire.NewSet(sessionSet, provideUserService, wire.Bind(new(service.UserService), new(*impl.UserServiceImpl)))

var createUserControllerInjectSet = wire.NewSet(provideCreateUserForm, userServiceSet, provideCreateUserController)

var editUserControllerInjectSet = wire.NewSet(provideUpdateUserForm, provideEditUserController, userServiceSet)

var deleteUserControllerInjectSet = wire.NewSet(provideDeleteUserController, userServiceSet)

var activateUserControllerInjectSet = wire.NewSet(provideActivateUserController, userServiceSet)

var deActivateUserControllerInjectSet = wire.NewSet(provideDeActivateUserController, userServiceSet)

var getUserInfoControllerInjectSet = wire.NewSet(provideGetUserInfoController, userServiceSet)

var changePasswordControllerInjectSet = wire.NewSet(provideChangePasswordController, provideChangePassForm, userServiceSet)

var authMiddlewareInjectSet = wire.NewSet(provideAuthMiddleware, redisSet, userServiceSet)

var authServiceSet = wire.NewSet(provideAuthService, redisSet, userServiceSet, wire.Bind(new(service.AuthService), new(*impl.AuthServiceImpl)))

var loginControllerInjectSet = wire.NewSet(provideLoginController, provideLoginForm, authServiceSet)

var logoutControllerInjectSet = wire.NewSet(provideLogoutController, authServiceSet)

var bookServiceSet = wire.NewSet(sessionSet, provideBookService, wire.Bind(new(service.BookService), new(*impl.BookServiceImpl)))

var createBookControllerInjectSet = wire.NewSet(provideCreatBookForm, provideCreateBookController, bookServiceSet)
